# Generated by Django 5.0.6 on 2024-06-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeview',
            name='valueInsert',
            field=models.CharField(default='Valor depositado', max_length=200),
        ),
    ]
